name = "ryy"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-09-02"

send_metrics = false

[[kv_namespaces]]
binding = "KV"
id = "bfa5b89e8c58419fa98f59d24c6ae1c5"

[vars]
NODE_VERSION = "23.1.0"
